### ISSUE TITLE
ghcr.io/rjmalagon/ollama-linux-amd-apu:gfx900-v0.12.2 failing with 4650G

### ISSUE THREAD

**Issue by e-minguez** [rjmalagon/ollama-linux-amd-apu#25]
### What is the issue?

I've been using the `ghcr.io/rjmalagon/ollama-linux-amd-apu:rocm-6.3.4-latest` image successfully https://github.com/rjmalagon/ollama-linux-amd-apu/issues/2 as:

```
podman run -p 11434:11434 --name ollama -e HSA_OVERRIDE_GFX_VERSION="9.0.0" --device=/dev/kfd --device=/dev/dri/renderD128 -v /ssdpool/ollama-models:/root/.ollama/models:Z --annotation run.oci.keep_original_groups=1 --entrypoint=/bin/sh ghcr.io/rjmalagon/ollama-linux-amd-apu:rocm-6.3.4-latest -c 'echo "#!/bin/sh\necho \"6.12.43-amd64\"" > /usr/bin/uname; /bin/ollama serve'
```

But now it seems the container image I need to use for my hardware is `ghcr.io/rjmalagon/ollama-linux-amd-apu:gfx900-v0.12.2` but it crashes.

### Relevant log output

```shell
="loaded runners" count=1
time=2025-10-16T09:53:45.309Z level=INFO source=server.go:1251 msg="waiting for llama runner to start responding"
time=2025-10-16T09:53:45.309Z level=INFO source=server.go:1289 msg="llama runner started in 7.68 seconds"

rocBLAS error: Cannot read /usr/lib/ollama/rocm/rocblas/library/TensileLibrary.dat: Illegal seek for GPU arch : gfx900
 List of available TensileLibrary Files :
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1150.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx90a.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1201.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1102.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1100.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx908.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1151.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1030.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1200.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1101.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx942.dat"
time=2025-10-16T09:53:45.433Z level=ERROR source=server.go:1459 msg="post predict" error="Post \"http://127.0.0.1:35985/completion\": EOF"
[GIN] 2025/10/16 - 09:53:45 | 200 |  8.281094881s |     169.254.1.2 | POST     "/api/chat"
time=2025-10-16T09:53:45.433Z level=ERROR source=server.go:425 msg="llama runner terminated" error="signal: aborted"
time=2025-10-16T09:53:45.531Z level=WARN source=server.go:1171 msg="llama runner process no longer running" sys=6 string="signal: aborted"
...
time=2025-10-16T09:54:11.841Z level=INFO source=server.go:1289 msg="llama runner started in 7.88 seconds"
time=2025-10-16T09:54:11.841Z level=INFO source=sched.go:470 msg="loaded runners" count=1
time=2025-10-16T09:54:11.841Z level=INFO source=server.go:1251 msg="waiting for llama runner to start responding"
time=2025-10-16T09:54:11.841Z level=INFO source=server.go:1289 msg="llama runner started in 7.88 seconds"

rocBLAS error: Cannot read /usr/lib/ollama/rocm/rocblas/library/TensileLibrary.dat: Illegal seek for GPU arch : gfx900
 List of available TensileLibrary Files :
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1150.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx90a.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1201.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1102.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1100.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx908.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1151.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1030.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1200.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1101.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx942.dat"
time=2025-10-16T09:54:11.943Z level=ERROR source=server.go:1459 msg="post predict" error="Post \"http://127.0.0.1:43937/completion\": EOF"
[GIN] 2025/10/16 - 09:54:11 | 500 | 13.455640296s |     169.254.1.2 | POST     "/api/chat"
time=2025-10-16T09:54:11.943Z level=ERROR source=server.go:425 msg="llama runner terminated" error="signal: aborted"
time=2025-10-16T09:54:12.032Z level=WARN source=server.go:1171 msg="llama runner process no longer running" sys=6 string="signal: aborted"
time=2025-10-16T09:54:12.032Z level=WARN source=server.go:1171 msg="llama runner process no longer running" sys=6 string="signal: aborted"
time=2025-10-16T09:54:12.032Z level=WARN source=amd_linux.go:151 msg="ollama recommends running the https://www.amd.com/en/support/download/linux-drivers.html" error="amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"
...
time=2025-10-16T09:54:26.138Z level=INFO source=server.go:1289 msg="llama runner started in 8.68 seconds"
time=2025-10-16T09:54:26.138Z level=INFO source=sched.go:470 msg="loaded runners" count=1
time=2025-10-16T09:54:26.138Z level=INFO source=server.go:1251 msg="waiting for llama runner to start responding"
time=2025-10-16T09:54:26.138Z level=INFO source=server.go:1289 msg="llama runner started in 8.68 seconds"

rocBLAS error: Cannot read /usr/lib/ollama/rocm/rocblas/library/TensileLibrary.dat: Illegal seek for GPU arch : gfx900
 List of available TensileLibrary Files :
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1150.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx90a.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1201.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1102.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1100.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx908.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1151.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1030.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1200.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx1101.dat"
"/usr/lib/ollama/rocm/rocblas/library/TensileLibrary_lazy_gfx942.dat"
time=2025-10-16T09:54:26.237Z level=ERROR source=server.go:1459 msg="post predict" error="Post \"http://127.0.0.1:46865/completion\": EOF"
time=2025-10-16T09:54:26.237Z level=ERROR source=server.go:425 msg="llama runner terminated" error="signal: aborted"
[GIN] 2025/10/16 - 09:54:26 | 500 | 14.289458447s |     169.254.1.2 | POST     "/api/chat"
```

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

ghcr.io/rjmalagon/ollama-linux-amd-apu:gfx900-v0.12.2

**Comment by rjmalagon** [comment]
Got this, I miss adding the correct LLVM target.

**Comment by rjmalagon** [comment]
Thanks for notice this.
Made ollama-linux-amd-apu:gfx900-v0.12.2 ROCM 6.3.4 based because it includes the correct target for GFX900 level hardware. You can pull it again to test the new changes.
```
TensileLibrary_lazy_gfx1010.dat
TensileLibrary_lazy_gfx1012.dat
TensileLibrary_lazy_gfx1030.dat
TensileLibrary_lazy_gfx1100.dat
TensileLibrary_lazy_gfx1101.dat
TensileLibrary_lazy_gfx1102.dat
TensileLibrary_lazy_gfx1151.dat
TensileLibrary_lazy_gfx1200.dat
TensileLibrary_lazy_gfx1201.dat
TensileLibrary_lazy_gfx900.dat
TensileLibrary_lazy_gfx906.dat
TensileLibrary_lazy_gfx908.dat
TensileLibrary_lazy_gfx90a.dat
TensileLibrary_lazy_gfx942.dat
```

**Comment by rjmalagon** [comment]
There is now experimental (buggy, slower than ROCM) Vulkan support on ghcr.io/rjmalagon/ollama-linux-amd-apu:optm-v0.12.6, enabled as default for unsupported GPUs that have Vulkan support (works "well" in my Ryzen 2000 APU test hardware on small models).

**Comment by e-minguez** [comment]
> Thanks for notice this. Made ollama-linux-amd-apu:gfx900-v0.12.2 ROCM 6.3.4 based because it includes the correct target for GFX900 level hardware. You can pull it again to test the new changes.
> 
> ```
> TensileLibrary_lazy_gfx1010.dat
> TensileLibrary_lazy_gfx1012.dat
> TensileLibrary_lazy_gfx1030.dat
> TensileLibrary_lazy_gfx1100.dat
> TensileLibrary_lazy_gfx1101.dat
> TensileLibrary_lazy_gfx1102.dat
> TensileLibrary_lazy_gfx1151.dat
> TensileLibrary_lazy_gfx1200.dat
> TensileLibrary_lazy_gfx1201.dat
> TensileLibrary_lazy_gfx900.dat
> TensileLibrary_lazy_gfx906.dat
> TensileLibrary_lazy_gfx908.dat
> TensileLibrary_lazy_gfx90a.dat
> TensileLibrary_lazy_gfx942.dat
> ```

confirmed working with that gfx900-v0.12.2 label, thanks!



> There is now experimental (buggy, slower than ROCM) Vulkan support on ghcr.io/rjmalagon/ollama-linux-amd-apu:optm-v0.12.6, enabled as default for unsupported GPUs that have Vulkan support (works "well" in my Ryzen 2000 APU test hardware on small models).

Does this mean that I should switch to that label instead?

**Comment by rjmalagon** [comment]
Maybe not right now. It would be recommended when the new Vulkan backend resolves its more basic bugs, the performance gap with ROCM shortens, and newer Ollama models and features outweigh the speed and stability of Ollama v0.12.2.

Keep an eye on new release features, do short tests.

**Comment by e-minguez** [comment]
As per https://github.com/rjmalagon/ollama-linux-amd-apu/releases/tag/v0.14.1 RN:

> Adopt upstream AMD GTT patches.

Does that mean 4650G users can use that image moving forward instead of the pinned gfx900-v0.12.2 one?

Thanks!

**Comment by e-minguez** [comment]
BTW I tried as:

```
podman run \
                -d -p 11434:11434 --replace \
                --name ollama -e HSA_OVERRIDE_GFX_VERSION="9.0.0" \
                --device=/dev/kfd --device=/dev/dri/renderD128 \
                -v /ssdpool/ollama-models:/root/.ollama/models:Z \
                --annotation run.oci.keep_original_groups=1 \
                --entrypoint=/bin/sh \
                ghcr.io/rjmalagon/ollama-linux-amd-apu:v0.14.1 \
                        -c 'echo "#!/bin/sh\necho \"6.12.43-amd64\"" > /usr/bin/uname; /bin/ollama serve'
```

But it doesn't seem to work:

```
Couldn't find '/root/.ollama/id_ed25519'. Generating new private key.
Your new public key is:

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPX0E+4RPxqBOs1hR8mI397C29bWrEgb82B+vvE/B/pP

time=2026-01-15T16:36:41.031Z level=INFO source=routes.go:1614 msg="server config" env="map[CUDA_VISIBLE_DEVICES: GGML_VK_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION:9.0.0 HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_CONTEXT_LENGTH:4096 OLLAMA_DEBUG:INFO OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/root/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NEW_ENGINE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://* vscode-file://*] OLLAMA_REMOTES:[ollama.com] OLLAMA_SCHED_SPREAD:false OLLAMA_VULKAN:false ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
time=2026-01-15T16:36:41.035Z level=INFO source=images.go:499 msg="total blobs: 15"
time=2026-01-15T16:36:41.035Z level=INFO source=images.go:506 msg="total unused blobs removed: 0"
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] HEAD   /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] GET    /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
[GIN-debug] HEAD   /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func3 (5 handlers)
[GIN-debug] GET    /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func4 (5 handlers)
[GIN-debug] POST   /api/pull                 --> github.com/ollama/ollama/server.(*Server).PullHandler-fm (5 handlers)
[GIN-debug] POST   /api/push                 --> github.com/ollama/ollama/server.(*Server).PushHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (5 handlers)
[GIN-debug] GET    /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (5 handlers)
[GIN-debug] POST   /api/show                 --> github.com/ollama/ollama/server.(*Server).ShowHandler-fm (5 handlers)
[GIN-debug] DELETE /api/delete               --> github.com/ollama/ollama/server.(*Server).DeleteHandler-fm (5 handlers)
[GIN-debug] POST   /api/me                   --> github.com/ollama/ollama/server.(*Server).WhoamiHandler-fm (5 handlers)
[GIN-debug] POST   /api/signout              --> github.com/ollama/ollama/server.(*Server).SignoutHandler-fm (5 handlers)
[GIN-debug] DELETE /api/user/keys/:encodedKey --> github.com/ollama/ollama/server.(*Server).SignoutHandler-fm (5 handlers)
[GIN-debug] POST   /api/create               --> github.com/ollama/ollama/server.(*Server).CreateHandler-fm (5 handlers)
[GIN-debug] POST   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).CreateBlobHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).HeadBlobHandler-fm (5 handlers)
[GIN-debug] POST   /api/copy                 --> github.com/ollama/ollama/server.(*Server).CopyHandler-fm (5 handlers)
[GIN-debug] GET    /api/ps                   --> github.com/ollama/ollama/server.(*Server).PsHandler-fm (5 handlers)
[GIN-debug] POST   /api/generate             --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (5 handlers)
[GIN-debug] POST   /api/chat                 --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (5 handlers)
[GIN-debug] POST   /api/embed                --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (5 handlers)
[GIN-debug] POST   /api/embeddings           --> github.com/ollama/ollama/server.(*Server).EmbeddingsHandler-fm (5 handlers)
[GIN-debug] POST   /v1/chat/completions      --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (6 handlers)
[GIN-debug] POST   /v1/completions           --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (6 handlers)
[GIN-debug] POST   /v1/embeddings            --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models                --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models/:model         --> github.com/ollama/ollama/server.(*Server).ShowHandler-fm (6 handlers)
[GIN-debug] POST   /v1/responses             --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (6 handlers)
[GIN-debug] POST   /v1/messages              --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (6 handlers)
[GIN-debug] POST   /v1/images/generations    --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.RegisterRoutes.func13 (5 handlers)
time=2026-01-15T16:36:41.036Z level=INFO source=routes.go:1667 msg="Listening on [::]:11434 (version 0.0.0)"
time=2026-01-15T16:36:41.039Z level=INFO source=runner.go:67 msg="discovering available GPUs..."
time=2026-01-15T16:36:41.039Z level=WARN source=runner.go:485 msg="user overrode visible devices" HSA_OVERRIDE_GFX_VERSION=9.0.0
time=2026-01-15T16:36:41.039Z level=WARN source=runner.go:489 msg="if GPUs are not correctly discovered, unset and try again"
time=2026-01-15T16:36:41.042Z level=INFO source=server.go:429 msg="starting runner" cmd="/usr/bin/ollama runner --ollama-engine --port 45045"
time=2026-01-15T16:36:41.238Z level=INFO source=runner.go:106 msg="experimental Vulkan support disabled.  To enable, set OLLAMA_VULKAN=1"
time=2026-01-15T16:36:41.238Z level=INFO source=server.go:429 msg="starting runner" cmd="/usr/bin/ollama runner --ollama-engine --port 36285"
time=2026-01-15T16:36:45.803Z level=INFO source=server.go:429 msg="starting runner" cmd="/usr/bin/ollama runner --ollama-engine --port 43325"
time=2026-01-15T16:36:45.803Z level=INFO source=server.go:429 msg="starting runner" cmd="/usr/bin/ollama runner --ollama-engine --port 41841"
time=2026-01-15T16:36:45.974Z level=INFO source=runner.go:464 msg="failure during GPU discovery" OLLAMA_LIBRARY_PATH="[/usr/lib/ollama /usr/lib/ollama/rocm_v7]" extra_envs="map[GGML_CUDA_INIT:1 ROCR_VISIBLE_DEVICES:0]" error="runner crashed"
time=2026-01-15T16:36:50.357Z level=INFO source=runner.go:464 msg="failure during GPU discovery" OLLAMA_LIBRARY_PATH="[/usr/lib/ollama /usr/lib/ollama/rocm_v6]" extra_envs="map[GGML_CUDA_INIT:1 ROCR_VISIBLE_DEVICES:0]" error="runner crashed"
time=2026-01-15T16:36:50.357Z level=INFO source=types.go:60 msg="inference compute" id=cpu library=cpu compute="" name=cpu description=cpu libdirs=ollama driver="" pci_id="" type="" total="62.2 GiB" available="61.1 GiB"
time=2026-01-15T16:36:50.357Z level=INFO source=routes.go:1708 msg="entering low vram mode" "total vram"="0 B" threshold="20.0 GiB"
```

**Comment by rjmalagon** [comment]
Unfortunately no, GFX900-level hardware was obsoleted for ROCM, You need to use the Vulkan backend instead.

> As per https://github.com/rjmalagon/ollama-linux-amd-apu/releases/tag/v0.14.1 RN:
> 
> > Adopt upstream AMD GTT patches.
> 
> Does that mean 4650G users can use that image moving forward instead of the pinned gfx900-v0.12.2 one?
> 
> Thanks!

**Comment by e-minguez** [comment]
I think I got it working!

```
podman run -it --rm -p 11434:11434 --name ollama --device=/dev/kfd --device=/dev/dri/renderD128 -v /ssdpool/ollama-models:/root/.ollama/models:Z --annotation run.oci.keep_original_groups=1 -e ROCR_VISIBLE_DEVICES=1 -e OLLAMA_VULKAN=1 ghcr.io/rjmalagon/ollama-linux-amd-apu:v0.14.1
Couldn't find '/root/.ollama/id_ed25519'. Generating new private key.
Your new public key is:

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICudYwuF3xj593DWdsJE1OPo0BMoHVY6b/RUBlzJq6oL

time=2026-01-16T14:26:51.488Z level=INFO source=routes.go:1614 msg="server config" env="map[CUDA_VISIBLE_DEVICES: GGML_VK_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_CONTEXT_LENGTH:4096 OLLAMA_DEBUG:INFO OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/root/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NEW_ENGINE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://* vscode-file://*] OLLAMA_REMOTES:[ollama.com] OLLAMA_SCHED_SPREAD:false OLLAMA_VULKAN:true ROCR_VISIBLE_DEVICES:1 http_proxy: https_proxy: no_proxy:]"
time=2026-01-16T14:26:51.491Z level=INFO source=images.go:499 msg="total blobs: 15"
time=2026-01-16T14:26:51.491Z level=INFO source=images.go:506 msg="total unused blobs removed: 0"
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] HEAD   /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] GET    /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
[GIN-debug] HEAD   /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func3 (5 handlers)
[GIN-debug] GET    /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func4 (5 handlers)
[GIN-debug] POST   /api/pull                 --> github.com/ollama/ollama/server.(*Server).PullHandler-fm (5 handlers)
[GIN-debug] POST   /api/push                 --> github.com/ollama/ollama/server.(*Server).PushHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (5 handlers)
[GIN-debug] GET    /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (5 handlers)
[GIN-debug] POST   /api/show                 --> github.com/ollama/ollama/server.(*Server).ShowHandler-fm (5 handlers)
[GIN-debug] DELETE /api/delete               --> github.com/ollama/ollama/server.(*Server).DeleteHandler-fm (5 handlers)
[GIN-debug] POST   /api/me                   --> github.com/ollama/ollama/server.(*Server).WhoamiHandler-fm (5 handlers)
[GIN-debug] POST   /api/signout              --> github.com/ollama/ollama/server.(*Server).SignoutHandler-fm (5 handlers)
[GIN-debug] DELETE /api/user/keys/:encodedKey --> github.com/ollama/ollama/server.(*Server).SignoutHandler-fm (5 handlers)
[GIN-debug] POST   /api/create               --> github.com/ollama/ollama/server.(*Server).CreateHandler-fm (5 handlers)
[GIN-debug] POST   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).CreateBlobHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).HeadBlobHandler-fm (5 handlers)
[GIN-debug] POST   /api/copy                 --> github.com/ollama/ollama/server.(*Server).CopyHandler-fm (5 handlers)
[GIN-debug] GET    /api/ps                   --> github.com/ollama/ollama/server.(*Server).PsHandler-fm (5 handlers)
[GIN-debug] POST   /api/generate             --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (5 handlers)
[GIN-debug] POST   /api/chat                 --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (5 handlers)
[GIN-debug] POST   /api/embed                --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (5 handlers)
[GIN-debug] POST   /api/embeddings           --> github.com/ollama/ollama/server.(*Server).EmbeddingsHandler-fm (5 handlers)
[GIN-debug] POST   /v1/chat/completions      --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (6 handlers)
[GIN-debug] POST   /v1/completions           --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (6 handlers)
[GIN-debug] POST   /v1/embeddings            --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models                --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models/:model         --> github.com/ollama/ollama/server.(*Server).ShowHandler-fm (6 handlers)
[GIN-debug] POST   /v1/responses             --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (6 handlers)
[GIN-debug] POST   /v1/messages              --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (6 handlers)
[GIN-debug] POST   /v1/images/generations    --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.RegisterRoutes.func13 (5 handlers)
time=2026-01-16T14:26:51.494Z level=INFO source=routes.go:1667 msg="Listening on [::]:11434 (version 0.0.0)"
time=2026-01-16T14:26:51.496Z level=INFO source=runner.go:67 msg="discovering available GPUs..."
time=2026-01-16T14:26:51.496Z level=WARN source=runner.go:485 msg="user overrode visible devices" ROCR_VISIBLE_DEVICES=1
time=2026-01-16T14:26:51.496Z level=WARN source=runner.go:489 msg="if GPUs are not correctly discovered, unset and try again"
time=2026-01-16T14:26:51.497Z level=INFO source=server.go:429 msg="starting runner" cmd="/usr/bin/ollama runner --ollama-engine --port 37717"
time=2026-01-16T14:26:51.670Z level=INFO source=server.go:429 msg="starting runner" cmd="/usr/bin/ollama runner --ollama-engine --port 46667"
time=2026-01-16T14:26:51.856Z level=INFO source=server.go:429 msg="starting runner" cmd="/usr/bin/ollama runner --ollama-engine --port 40267"
time=2026-01-16T14:26:52.035Z level=INFO source=types.go:42 msg="inference compute" id=00000000-0a00-0000-0000-000000000000 filter_id="" library=Vulkan compute=0.0 name=Vulkan0 description="AMD Radeon Graphics (RADV RENOIR)" libdirs=ollama,vulkan driver=0.0 pci_id=0000:0a:00.0 type=iGPU total="31.6 GiB" available="31.6 GiB"
[GIN] 2026/01/16 - 14:27:05 | 200 |     667.881µs |       127.0.0.1 | HEAD     "/"
[GIN] 2026/01/16 - 14:27:05 | 200 |     815.217µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2026/01/16 - 14:27:10 | 200 |      21.611µs |       127.0.0.1 | HEAD     "/"
[GIN] 2026/01/16 - 14:27:10 | 200 |  144.535727ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2026/01/16 - 14:27:10 | 200 |  126.383773ms |       127.0.0.1 | POST     "/api/show"
time=2026-01-16T14:27:10.599Z level=INFO source=server.go:429 msg="starting runner" cmd="/usr/bin/ollama runner --ollama-engine --port 36935"
time=2026-01-16T14:27:10.662Z level=WARN source=cpu_linux.go:130 msg="failed to parse CPU allowed micro secs" error="strconv.ParseInt: parsing \"max\": invalid syntax"
time=2026-01-16T14:27:10.743Z level=INFO source=server.go:245 msg="enabling flash attention"
time=2026-01-16T14:27:10.743Z level=INFO source=server.go:429 msg="starting runner" cmd="/usr/bin/ollama runner --ollama-engine --model /root/.ollama/models/blobs/sha256-e6a7edc1a4d7d9b2de136a221a57336b76316cfe53a252aeba814496c5ae439d --port 36345"
time=2026-01-16T14:27:10.744Z level=INFO source=sched.go:452 msg="system memory" total="62.2 GiB" free="61.8 GiB" free_swap="0 B"
time=2026-01-16T14:27:10.744Z level=INFO source=sched.go:459 msg="gpu memory" id=00000000-0a00-0000-0000-000000000000 library=Vulkan available="31.1 GiB" free="31.6 GiB" minimum="457.0 MiB" overhead="0 B"
time=2026-01-16T14:27:10.744Z level=INFO source=server.go:755 msg="loading model" "model layers"=37 requested=-1
time=2026-01-16T14:27:10.756Z level=INFO source=runner.go:1405 msg="starting ollama engine"
time=2026-01-16T14:27:10.756Z level=INFO source=runner.go:1440 msg="Server listening on 127.0.0.1:36345"
time=2026-01-16T14:27:10.767Z level=INFO source=runner.go:1278 msg=load request="{Operation:fit LoraPath:[] Parallel:1 BatchSize:512 FlashAttention:Enabled KvSize:4096 KvCacheType: NumThreads:6 GPULayers:37[ID:00000000-0a00-0000-0000-000000000000 Layers:37(0..36)] MultiUserCache:false ProjectorPath: MainGPU:0 UseMmap:false}"
time=2026-01-16T14:27:10.798Z level=INFO source=ggml.go:136 msg="" architecture=qwen3 file_type=Q4_K_M name="DeepSeek R1 0528 Qwen3 8B" description="" num_tensors=399 num_key_values=33
load_backend: loaded CPU backend from /usr/lib/ollama/libggml-cpu-haswell.so
ggml_vulkan: Found 1 Vulkan devices:
ggml_vulkan: 0 = AMD Radeon Graphics (RADV RENOIR) (radv) | uma: 1 | fp16: 1 | bf16: 0 | warp size: 64 | shared memory: 65536 | int dot: 0 | matrix cores: none
load_backend: loaded Vulkan backend from /usr/lib/ollama/vulkan/libggml-vulkan.so
time=2026-01-16T14:27:10.837Z level=INFO source=ggml.go:104 msg=system CPU.0.SSE3=1 CPU.0.SSSE3=1 CPU.0.AVX=1 CPU.0.AVX2=1 CPU.0.F16C=1 CPU.0.FMA=1 CPU.0.BMI2=1 CPU.0.LLAMAFILE=1 CPU.1.LLAMAFILE=1 compiler=cgo(gcc)
ggml_backend_vk_get_device_memory called: uuid 00000000-0a00-0000-0000-000000000000
ggml_backend_vk_get_device_memory called: luid 0x0000000000000000
time=2026-01-16T14:27:10.852Z level=INFO source=runner.go:1278 msg=load request="{Operation:alloc LoraPath:[] Parallel:1 BatchSize:512 FlashAttention:Enabled KvSize:4096 KvCacheType: NumThreads:6 GPULayers:37[ID:00000000-0a00-0000-0000-000000000000 Layers:37(0..36)] MultiUserCache:false ProjectorPath: MainGPU:0 UseMmap:false}"
ggml_backend_vk_get_device_memory called: uuid 00000000-0a00-0000-0000-000000000000
ggml_backend_vk_get_device_memory called: luid 0x0000000000000000
time=2026-01-16T14:27:11.362Z level=INFO source=runner.go:1278 msg=load request="{Operation:commit LoraPath:[] Parallel:1 BatchSize:512 FlashAttention:Enabled KvSize:4096 KvCacheType: NumThreads:6 GPULayers:37[ID:00000000-0a00-0000-0000-000000000000 Layers:37(0..36)] MultiUserCache:false ProjectorPath: MainGPU:0 UseMmap:false}"
time=2026-01-16T14:27:11.362Z level=INFO source=device.go:240 msg="model weights" device=Vulkan0 size="4.5 GiB"
time=2026-01-16T14:27:11.362Z level=INFO source=ggml.go:482 msg="offloading 36 repeating layers to GPU"
time=2026-01-16T14:27:11.362Z level=INFO source=ggml.go:489 msg="offloading output layer to GPU"
time=2026-01-16T14:27:11.362Z level=INFO source=ggml.go:494 msg="offloaded 37/37 layers to GPU"
time=2026-01-16T14:27:11.362Z level=INFO source=device.go:245 msg="model weights" device=CPU size="333.8 MiB"
time=2026-01-16T14:27:11.362Z level=INFO source=device.go:251 msg="kv cache" device=Vulkan0 size="576.0 MiB"
time=2026-01-16T14:27:11.362Z level=INFO source=device.go:262 msg="compute graph" device=Vulkan0 size="100.0 MiB"
time=2026-01-16T14:27:11.362Z level=INFO source=device.go:267 msg="compute graph" device=CPU size="8.0 MiB"
time=2026-01-16T14:27:11.362Z level=INFO source=device.go:272 msg="total memory" size="5.5 GiB"
time=2026-01-16T14:27:11.362Z level=INFO source=sched.go:526 msg="loaded runners" count=1
time=2026-01-16T14:27:11.362Z level=INFO source=server.go:1347 msg="waiting for llama runner to start responding"
time=2026-01-16T14:27:11.363Z level=INFO source=server.go:1381 msg="waiting for server to become available" status="llm server loading model"
time=2026-01-16T14:27:16.879Z level=INFO source=server.go:1385 msg="llama runner started in 6.13 seconds"
```

**Comment by rjmalagon** [comment]
The Vulkan backend is fairly good. Mostly by the good quality of open-source Vulkan drivers and the growing optimization/maturation of Vulkan math code. 

I don't doubt that the eventual retrofitting of Vulkan advances on our fairly old APUs will shorten the performance gap to ROCM and Cuda backends.
